labels:
  - label: "ShipAndVoyage"
    key: "Таможенный пост"
    postprocessing: "replace_symbols_and_letters"
    validations: "is_validate_for_ship_and_voyage"

config_of_table:
  length_of_kernel: 150
  min_width_of_cell: 7
  min_height_of_cell: 7
  indent_x_text_of_cells: 2
  indent_y_text_of_cells: 1
  config_for_pytesseract: "--oem 3 --psm 3"

config_of_database:
  database: "idp_db"
  user: "idp_admin"
  password: "w8g8GyOYLR83"
  host: "IDP_postgres_container"
  port: "5432"
  table: "port"




