port:
  name: port
  folder: "files/classification/port"
  key: "Поручение на погрузку"
  config: "port.yml"


line:
  name: line
  folder: "files/classification/line"
  key: "Аркас Раша"
  config: "line.yml"


unknown:
  name: unknown
  folder: "files/classification/unknown"
  key: None
